# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hw1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 368)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn1_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_1.setGeometry(QtCore.QRect(20, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn1_1.setFont(font)
        self.btn1_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn1_1.setCheckable(False)
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_2.setGeometry(QtCore.QRect(20, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn1_2.setFont(font)
        self.btn1_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn1_2.setCheckable(False)
        self.btn1_2.setObjectName("btn1_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn2_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn2_1.setGeometry(QtCore.QRect(20, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_1.setFont(font)
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn2_2.setGeometry(QtCore.QRect(20, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_2.setFont(font)
        self.btn2_2.setObjectName("btn2_2")
        self.btn2_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn2_3.setGeometry(QtCore.QRect(20, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_3.setFont(font)
        self.btn2_3.setObjectName("btn2_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 20, 201, 311))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn3_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn3_1.setGeometry(QtCore.QRect(20, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_1.setFont(font)
        self.btn3_1.setObjectName("btn3_1")
        self.btn3_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn3_2.setGeometry(QtCore.QRect(20, 70, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_2.setFont(font)
        self.btn3_2.setObjectName("btn3_2")
        self.groupBox_3_1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_3_1.setGeometry(QtCore.QRect(20, 120, 161, 131))
        self.groupBox_3_1.setObjectName("groupBox_3_1")
        self.label = QtWidgets.QLabel(self.groupBox_3_1)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3_1)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.btn3_3 = QtWidgets.QPushButton(self.groupBox_3_1)
        self.btn3_3.setGeometry(QtCore.QRect(10, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_3.setFont(font)
        self.btn3_3.setObjectName("btn3_3")
        self.btn3_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn3_4.setGeometry(QtCore.QRect(20, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_4.setFont(font)
        self.btn3_4.setObjectName("btn3_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(500, 20, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn4_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn4_1.setGeometry(QtCore.QRect(20, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn4_1.setFont(font)
        self.btn4_1.setObjectName("btn4_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Histogram Equalization"))
        self.btn1_1.setText(_translate("MainWindow", "1.1 Original image histogram"))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Equalized image histogram"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Hough Circle Tarnsformation and Histogram"))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Hough circle"))
        self.btn2_2.setText(_translate("MainWindow", "2.2 Hue histogram"))
        self.btn2_3.setText(_translate("MainWindow", "2.3 Back projection"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3. Camera Calibration"))
        self.btn3_1.setText(_translate("MainWindow", "3.1 Corner detection"))
        self.btn3_2.setText(_translate("MainWindow", "3.2 Intrinsic martix"))
        self.groupBox_3_1.setTitle(_translate("MainWindow", "3.3 Extrinsic Matrix"))
        self.label.setText(_translate("MainWindow", "select image"))
        self.btn3_3.setText(_translate("MainWindow", "3.3 Extrinsic matrix"))
        self.btn3_4.setText(_translate("MainWindow", "3.4 Distortion matrix"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4. Augumented Reality"))
        self.btn4_1.setText(_translate("MainWindow", "4.1 Augumented reality"))

